### ISSUE TITLE
isn't possible anymore to read translation from json?

### ISSUE THREAD

**Issue by Hasankanso** [channdara/flutter_translator#6]
Hello there,

we have 3 json translation in our project, but after an update, the only way to init the package is by passing maps that includes all translations, is it intended to remove json option?

thank you

**Comment by channdara** [comment]
@Hasankanso Hello there.

Yes, we remove the JSON file support from the package. We found some minor problems and performance with loading file assets, especially with low-end devices. That's why we come to the conclusion of removing it. Another thing is, that it's easier to call and modify the key of the translated text from the Map Data than the JSON file.

**Comment by Hasankanso** [comment]
> @Hasankanso Hello there.
> 
> 
> 
> Yes, we remove the JSON file support from the package. We found some minor problems and performance with loading file assets, especially with low-end devices. That's why we come to the conclusion of removing it. Another thing is, that it's easier to call and modify the key of the translated text from the Map Data than the JSON file.

Okay, thank you for your response
